#! /bin/sh

sxhkd &

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
#setxkbmap -option caps:swapescape &

feh --bg-fill $HOME/Pictures/wallpaper.png &

killall -q polybar ;

polybar -c $HOME/.config/polybar/config right &
polybar -c $HOME/.config/polybar/config left &

#wmname LG3D &

xrandr --output DP-1 --mode 2560x1440 --primary
xrandr --output DP-1-5 --mode 2560x1440 --right-of DP-1

picom  &

bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor DP-1-5 -d 6 7 8 9 0

bspc config border_width         3
bspc config window_gap          10
bspc config top_padding	        15

#bspc config normal_border_color "#04030f"
#bspc config focused_border_color "#9198ff"
#bspc config urgent_border_color "#FF0000"

bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus true

#bspc monitor eDP-1 -n 0 -d I II III IV V
# Extended monitor for laptop
#bspc monitor HDMI-1 -d I II III IV V


###

bspc rule -a R_x11 state=floating
#bspc config external_rules_command $HOME/.bin/float_win.sh


